# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0005_auto_20161129_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='experience',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
