# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 01:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UniversitiesApp', '0006_merge_20161128_1926'),
        ('CompaniesApp', '0003_merge_20161128_1926'),
        ('AuthenticationApp', '0005_auto_20161127_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('about', models.CharField(blank=True, max_length=500, null=True)),
                ('almamater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='almamater', to='UniversitiesApp.University')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engineer_company', to='CompaniesApp.Company')),
            ],
        ),
    ]
