# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0006_auto_20161201_2156'),
        ('AuthenticationApp', '0005_auto_20161127_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='bookmarks',
            field=models.ManyToManyField(to='ProjectsApp.Project'),
        ),
    ]
