# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0006_myuser_bookmarks'),
        ('AuthenticationApp', '0006_engineer'),
    ]

    operations = [
    ]
