# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 21:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0007_merge_20161202_1914'),
        ('AuthenticationApp', '0008_auto_20161202_1039'),
    ]

    operations = [
    ]
