# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0009_student_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_university', to='UniversitiesApp.University'),
        ),
    ]
