# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 03:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0009_merge_20161203_2142'),
        ('AuthenticationApp', '0013_auto_20161205_1423'),
    ]

    operations = [
    ]
