# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0014_auto_20161206_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='groups',
            field=models.ManyToManyField(to='GroupsApp.Group'),
        ),
    ]
