# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniversitiesApp', '0007_course_teacher'),
        ('AuthenticationApp', '0015_auto_20161206_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='classes',
            field=models.ManyToManyField(related_name='teacher_courses', to='UniversitiesApp.Course'),
        ),
    ]
