# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniversitiesApp', '0007_course_teacher'),
        ('AuthenticationApp', '0016_teacher_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classes',
            field=models.ManyToManyField(related_name='student_courses', to='UniversitiesApp.Course'),
        ),
    ]
