# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0007_project_created_by'),
        ('AuthenticationApp', '0017_student_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='projects',
            field=models.ManyToManyField(null=True, related_name='engineer_projects', to='ProjectsApp.Project'),
        ),
    ]
