# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0017_student_classes'),
        ('AuthenticationApp', '0014_merge_20161206_0354'),
    ]

    operations = [
    ]
