# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0018_engineer_projects'),
        ('AuthenticationApp', '0018_merge_20161207_1556'),
    ]

    operations = [
    ]
