# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0018_engineer_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='skills',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
