# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 05:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0019_merge_20161207_1843'),
        ('AuthenticationApp', '0019_student_skills'),
    ]

    operations = [
    ]
